site_name: Square 9 Documentation
site_url: https://sitename.example/
nav:
  - Home: index.md
  - GlobalCapture:
    - GlobalCapture Overview: GlobalCapture.md
    - Nodes:
      - Repeate Node: Repeat.md
      

extra_css:
  - stylesheets/extra.css
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  logo: assets/S9 Logo White.png
  favicon: assets/S9Logo.ico
  features:
    - navigation.footer
    - navigation.indexes
    - navigation.path
    - navigation.top
  palette:
    # Dark Mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
          icon: material/weather-sunny
          name: Dark mode
      primary: custom
      accent: custom
      

    # Light Mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: custom
      accent: custom

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - md_in_html
  - pymdownx.blocks.caption
extra:
  social:
    - icon: simple/youtube
      link: https://www.youtube.com/@Square9Softworks
    - icon: simple/linkedin
      link: https://linkedin.com
  version:
    provider: mike
plugins:
  - mike:
      # These fields are all optional; the defaults are as below...
      alias_type: symlink
      redirect_template: null
      deploy_prefix: ''
      canonical_version: null
      version_selector: true
      css_dir: css
      javascript_dir: js
copyright: Copyright &copy; 2024 Square 9 Softworks